### ISSUE TITLE
Proposal: Functional Interface Programming

### ISSUE THREAD

**Issue by martinklepsch** [berlinjs/berlinjs.org#105]
_Doing this as an issue for now as index.html contains Februarys talks._

**Potential description:**

> In the last couple of weeks I spent some time playing with Clojurescript learning about how to build UIs in a functional way. 
> Amazed by the things I encountered on that field-trip I want to introduce you to some of the basic patterns and ideas and compare them to more traditional approaches like MVC.
> Probably there will be some code but I want to focus on the concepts rather than specific implementations.

Any feedback/suggestions appreciated :)

**Comment by rmehner** [comment]
+1 to your proposal. You can also just open the PR with your talk and we'll just merge it after the February meetup.

**Comment by martinklepsch** [comment]
I made a PR #110.
