### ISSUE TITLE
The CITGM Diaries

### ISSUE THREAD

**Issue by MylesBorins** [berlinjs/berlinjs.org#226]
# The CITGM Diaries

> *Note* I'm already speaking in town this week, so I'd prefer that if there are other newer speakers who would like the opportunity that it be given to them, I wanted to offer some content just in case. It is not that I wouldn't love to talk, just don't need to hog the stage :P

## Abstract

The Canary in the Gold Mine is a smoke testing utility that automates running
unit tests of various various modules in the Node.js ecosystem, it must pass for
all controversial changes and releases. CITGM has been incredibly successful,
finding all sorts of regressions across the ecosystem and in node core itself.

I have kept a diary of all the weirdness, lets examine how things break!

## A bit more info

The Canary in the Gold Mine (CITGM) is a smoketesting utility used by the Node.js
project to test for ecosystem breakages. CITGM is able to download the source of a
module published to npm, install all the dependencies, and run it's test suite. When
the project is going to make a release or land a controversial change we are able to
automate the test suites of 70 of the top modules in the ecosystem to confirm we are
not causing unexpected breakages.

This talk will outline how CITGM works, how it fits within node.js CI, and some of
the interesting edge cases we have experienced. We will dig into the architecture of
the utility itself and look at how it is set up in Jenkins. We will also do 3
different case studies of major breakages that would not have been found with CITGM.

**Comment by rmehner** [comment]
Hey Myles, is this for the JSConf special on May 4th or for our regular meetup on May 18th?

**Comment by MylesBorins** [comment]
for JSConf special.

**Comment by rmehner** [comment]
That already has a full lineup. The abstract sounds super nice tho :/

This is an evening event which starts around 7pm, so 4 talks is already plenty. Sorry! There was this idea of lightning talks, do you think you'd be able to break this thing down to 5 minutes, something like: "This was clearly the weirdest breaking thing I've encountered and we have CITGM in place for that"? I don't know, just throwing thoughts :)

**Comment by MylesBorins** [comment]
I can definitely make some sort of lightening talk. FWIW I mostly just wanted to make sure there was content... super happy there is already enough content!

**Comment by rmehner** [comment]
So if you wanna make this a lightning talk, I'm sure we'll find a way to work this in and as I've said, it's indeed quite interesting :)

Thanks Myles and I hope you enjoy Berlin so far :)
