### ISSUE TITLE
Call for Speakers – November 2017

### ISSUE THREAD

**Issue by verpixelt** [berlinjs/berlinjs.org#239]
# How to submit a talk to BerlinJS?
You can either comment on this issue or send us an email at (insert email address – we need an address everyone has access to)

### When and where will it be?
- November 16th
- Adalbertstraße 8, 10999 Berlin, Germany

### What should I talk about?
Anything JavaScript (JavaScript / JavaScript community related), that gets you excited.

### Do I need to be an expert to talk?
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

### How long should my talk be?
Between five and twentyfive minutes. There won’t be any formal Q&A.

### What should be in my talk submission?
Your name, Twitter handle / email address, talk title and a few sentences describing what you want to talk about would be great.

### What's the A/V situation?
We'll have a projector (Full HD / HDMI) and a mic for you to use. Adapters are available.

**Comment by lrlna** [comment]
Hello :wave:! I wanna give a talk about [merry](https://github.com/shipharbor/merry). 

# A merry story of Merry, a merry http framework.

## Abstract:
Your backend application should be about patterns you can create and follow. Introducing Merry -- a small, cute streaming `HTTP` framework, with a simple router and middleware solutions. This tiny wrapper around `HTTP` handles the basics, and lets you create composable solutions for your backend needs. 

In this talk, we will cover some of Merry's internals and simple patterns you can use for logging, performance monitoring, and error handling that you can take away to your own backend applications, regardless of the framework you use. 🌊 ⛵️ 🌊. 

## Deets:
- twitter: [@_lrlna](https://twitter.com/_lrlna)
- name: Irina Shestak

Thanks ^___^
