### ISSUE TITLE
Call for Speakers – April 2018

### ISSUE THREAD

**Issue by felixjung** [berlinjs/berlinjs.org#246]
# How to submit a talk to BerlinJS?
You can either comment on this issue or send us an email at (insert email address – we need an address everyone has access to)

### When and where will it be?
- April 19th
- Adalbertstraße 8, 10999 Berlin, Germany

### What should I talk about?
Anything JavaScript (JavaScript / JavaScript community related), that gets you excited.

### Do I need to be an expert to talk?
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

### How long should my talk be?
Between five and twentyfive minutes. There won’t be any formal Q&A.

### What should be in my talk submission?
Your name, Twitter handle / email address, talk title and a few sentences describing what you want to talk about would be great.

### What's the A/V situation?
We'll have a projector (Full HD / HDMI) and a mic for you to use. Adapters are available.

**Comment by felixjung** [comment]
Steven Syrek
@sjsyrek on Twitter, GitHub, Medium, and most other places
Make a Lambda Calculus: Functional Programming in JavaScript... without JavaScript
Functional programming concepts have the reputation of being hard to learn. If we start from first principles, however, they don't have to be. In this talk, I'll demonstrate how we can implement the entire universe of FP from scratch, using only JavaScript arrow functions.
I have done this as a 2 hour workshop, but I happy to condense it into a 20-30 minute "taster" for this meetup.

**Comment by felixjung** [comment]
## Name

Stefan Judis

## Online presence

stefanjudis.com
https://twitter.com/stefanjudis
https://github.com/stefanjudis/

## Talk title

I didn't know that!

## Abstract

In 2017 I discovered ~50  things in WebDev that were unknown to me. These are now documented on my blog. The fun thing is that these are sometimes very advanced but sometimes also very basic. 

I want to share a lot of nitty-gritty details of JavaScript but also want to take away the fear of the audience to say "I don't know that" and show the power of starting a routine that helps to gain and remember knowledge.

## Note

I'll focus on the JS part and not talk about other things. :)

**Comment by felixjung** [comment]
#### Name:
Praveen Kumar

`Twitter`: https://twitter.com/_praveen612
`Gmail`: pdnsjce
`GitHub`: https://github.com/praveen612

#### Talk title:
migrating to webpack 4

#### Abstract:
Recently upgraded an application at work from webpack 3 to 4.
Want to share some metrics and things I have learned while doing this.
I think its around 10 to 15 min talk with some code samples to show.

**Comment by Mohamed3on** [comment]
I think this is a bit confusing, this issue says you should submit talks here or via -a still unknown- email, but the README says you should submit via a pull request. Which one is it?

**Comment by rmehner** [comment]
@Mohamed3on all of it :) Will clear that up in the README soon.

Email is "submit@berlinjs.org"
