### ISSUE TITLE
Proposal: Cycle.js: UI as Pure Functions of Time

### ISSUE THREAD

**Issue by atomrc** [berlinjs/berlinjs.org#252]
##### Talk title

Cycle.js: UI as Pure Functions of Time

##### Abstract

What if we considered Time as a fundamental input of our programs

###### Your name

Thomas Belin

###### Means to get in touch with you

Twitter: @atomrc

**Comment by carolstran** [comment]
Hey @atomrc! Sorry for the massive delay in response. I was wondering if you would still be interested in giving this talk. And if so, how long it would be and if you have a more detailed abstract.

I can't guarantee anything at the moment, but we're trying to figure out what we're working with in 2019 and a better way to structure our proposal process in the future 😊

**Comment by carolstran** [comment]
One more question (if you're still interested), will this be your first time speaking or have you given talks before?

**Comment by carolstran** [comment]
👋 @atomrc, just checking in on this to see if you're still interested in speaking. If you don't reply within a week or so then I'll close the issue (mostly to keep everything organized) - but of course, you can always open a new one 😁

**Comment by atomrc** [comment]
Hey @carolstran :)

I would still be interested in talking at Berlin JS. Thing is, I will have pretty limited free time until mid-April.
The May session (or later) could work for me :)

**Comment by carolstran** [comment]
Yay great! That works well for us actually. Maybe we can get in touch again in late March/early April? We haven't sorted out Q2 yet but should have a better idea then. 

Would you want to do the same talk you originally proposed or a different one? Also, would this be your first time speaking?

**Comment by atomrc** [comment]
Sounds great, let's sync late March/ early April :+1: 

I will give the same talk as proposed (I just need to refresh it). 
It will not be my first talk, I have given a bunch (you can find a list and some videos here http://blog.thomasbelin.fr/talks/)

Looking forward to speaking at BerlinJS :)

**Comment by carolstran** [comment]
Hey hey @atomrc syncing as promised, just a little later 😅 Would you want to present in May? We have a spot open 🙌 If May doesn't work for you, just let me know which month would. I think any month except June works for us!

**Comment by atomrc** [comment]
Hey @carolstran When would it be in May?
It could totally work for me if it's after the 12th :)

**Comment by carolstran** [comment]
It would be the 16th. Does that work? 😁

**Comment by atomrc** [comment]
Let's do this :)

**Comment by carolstran** [comment]
Perfect! We have you down ✅

**Comment by carolstran** [comment]
Hey @atomrc, just wanted to confirm that you're still available for speaking next week. If so, could you send us a talk description? That way we can update the website and announce this week 😇 Thanks!

**Comment by atomrc** [comment]
Hey @carolstran yes I am still available and looking forward :)

So here is a more detailed description of the talk:

Time is at the source of every single interaction that occurs in an application. 
Click events, http responses, websocket messages, timers... They all depend on Time but the code we write for our interfaces seem to want to get rid of the temporal dimension as soon as possible.
Reactive Programming is here to bring back Time into our code and Cycle.js pushes that concept to its limits. 
During that talk, we will see how we can, in a declarative programming style, design interfaces that are pure functions of Time.

**Comment by carolstran** [comment]
Excellent @atomrc! I just updated the website. Check it out and let me know if you want anything changed: https://berlinjs.org/

If it looks ok, then we'll announce tomorrow!

**Comment by carolstran** [comment]
Once again, super lovely talk! Finally closing this issue and thanks again 🎉

**Comment by atomrc** [comment]
Thanks @carolstran . Was a real pleasure to talk at Berlinjs :)
