### ISSUE TITLE
Ember.js talk

### ISSUE THREAD

**Issue by yarigpopov** [berlinjs/berlinjs.org#254]
##### Talk title

If you haven't use Ember.js before its the right moment to try.

##### Abstract
You might ask, isn't Ember.js dead now? Isn't it gone in vain and only crazy guys left supporting some legacy applications hoping to rewrite everything in React and Redux? Dead wrong.

Although Ember.js was around for 5 last years, it wasn't a mainstream ever. Mostly due to the fact that no big companies with unlimited marketing resources were supporting it. But last year, after LinkedIn invested a lot into Ember.js it starts gaining momentum. It used also in Netflix, Heroku, Digital Ocean, Intercom and Siemens. 

Maybe you have make a closer look to this framework? And if yes, where to start?

###### Your name
Iaroslav Popov

###### Means to get in touch with you
chilicoder in berlin.js slack
https://twitter.com/chilicoder
@chilicoder

**Comment by carolstran** [comment]
Hey @chilicoder! Sorry for the massive delay in response. I was wondering if you would still be interested in giving this talk. And if so, how long would it be?

I can't guarantee anything at the moment, but we're trying to figure out what we're working with in 2019 and a better way to structure our proposal process in the future 😊

**Comment by carolstran** [comment]
One more question (if you're still interested), will this be your first time speaking or have you given talks before?

**Comment by yarigpopov** [comment]
Hi Carolyn,
I was thinking about 15-20 minutes talk. But it can be more if necessary.
And I did a couple of talks before in auditories around 50 people

**Comment by carolstran** [comment]
Awesome thanks 🙌

**Comment by carolstran** [comment]
Hey hey @chilicoder, another question for you 😅 Would you have any month(s) that would work especially well (or don't work) for you in 2019? We're on the third Thursday of each month.

**Comment by yarigpopov** [comment]
Hi @carolstran 
There is chance that you won't be able to do it in May and maybe July. Other months fit me. At least AFAIK

**Comment by carolstran** [comment]
Would you be interested in presenting on March 21? No pressure, just throwing it out there 😊

**Comment by yarigpopov** [comment]
Let me think about it until next week. There is a yearly Emberconf on 18-20. There is a marginal chance i go (its in US)
If not 21 would be great, I can share last news

**Comment by yarigpopov** [comment]
And in case you asking why I haven’t mentioned March before, I checked the dates today ☺️

**Comment by carolstran** [comment]
No problem! Just let us know once you know whether or not you're going to the US. There's no urgency on our end, the spot is yours if you want it 😊

**Comment by carolstran** [comment]
Hey, quick update on our end - We have a speaker who will only be in Berlin during March. So would it be alright if you presented in April? Or any other month you want really, at this point you'd have full choice 😂 Just let me know what you think!

**Comment by yarigpopov** [comment]
Hi! Fine for me. Maybe, April is even better. Then I will aim on April

**Comment by carolstran** [comment]
Awesome thank you! It'll be on Thursday, April 18. I'll count you in for April, then if something comes up and you can't make it just let me know and we can reschedule.

**Comment by carolstran** [comment]
Hey @chilicoder, just wanted to check in and see if March still works. If so, I'll be updated the website with your talk info this week - so let me know if you want to change anything from the proposal 😊 Thank you!

**Comment by carolstran** [comment]
If you saw an alert for my previous message, please ignore as I mixed up the dates 😇  Looking forward to having you in April!

**Comment by carolstran** [comment]
Hey hey @chilicoder! We updated the website with the info for the April meetup. Can you check it out and let us know if anything is wrong/you'd like to change something? https://berlinjs.org/

We're aiming to announce the meetup later this week 🎉

**Comment by yarigpopov** [comment]
Looks good

What is the timebox? 20 minutes?

**Comment by carolstran** [comment]
Thanks! And yeah, if you could keep it between 15-20 minutes - would be excellent 👌

**Comment by carolstran** [comment]
Closing this as you already delivered your talk. Thanks again! 👏
