### ISSUE TITLE
Talk proposal: Prototyping matters!

### ISSUE THREAD

**Issue by hwclass** [berlinjs/berlinjs.org#255]
##### Talk title

Javascript ecosystem is bigger than it is used to be and there are a number of options. But what about if we choose the best/optimum alternatives to have something done or not? 

##### Abstract

Sometimes it can be a problem to start from somewhere to immediately prove the concept of what we have on our minds in terms of architectural decisions, tech stack and the other tiny but critical details. Steps to deliver a new "thing" may be a problem if the choices are made in a wrong/immediate fashion. So I would like to tell the very first steps to know the balance what a greenfield project needs and how developer gets satisfaction from what she/he will build.  

###### Your name

Baris Guler

###### Means to get in touch with you

harderworking.class@gmail.com
https://twitter.com/hwclass
https://github.com/hwclass

**Comment by carolstran** [comment]
Hey @hwclass! So weird to be messaging you on something other than a Blacklane repo 😄Sorry for the massive delay in response on this. I was wondering if you would still be interested in giving this talk. And if so, how long would it be?

I can't guarantee anything at the moment, but we're trying to figure out what we're working with in 2019 and a better way to structure our proposal process in the future 😊

**Comment by carolstran** [comment]
👋 @hwclass, just checking in on this to see if you're still interested in speaking. If you don't reply here then I'll bug you at work hehe but if you're no longer interested I'll close the issue (mostly to keep everything organized) - but of course, you can always open a new one 😁

**Comment by carolstran** [comment]
👋 Closing this now, but feel free to reopen or open a new issue if you're interested in speaking in the future!
