### ISSUE TITLE
TC39: Language Design in the Open

### ISSUE THREAD

**Issue by codehag** [berlinjs/berlinjs.org#256]
This talk is meant to drum up some interest in the upcoming tc39 panel!

##### Talk title
TC39: Language Design in the Open

##### Abstract
Have you ever wondered how JavaScript gets specified? Or been confused as to why certain decisions are made? A language like JavaScript, with a large diverse user space, is half designed, and half reverse engineered. Like all web standards, JavaScript is developed in conjunction with the realities of the web and user decisions in how the language is used and formed. This results in unique backwards compatibility issues such as the recent `smooshGate` discussion. This talk will discuss constraints, mediation strategies and issues that have arisen over the years. 

###### Your name

Yulia Startsev

###### Means to get in touch with you

Twitter: @ioctaptceb

**Comment by carolstran** [comment]
👋 @codehag! I'm going to close this issue (long overdue, huh 😄) Thanks again for a great talk last year 💯
