### ISSUE TITLE
Talk submission for May 17th (LoveBits, runnable code poems)

### ISSUE THREAD

**Issue by muratkemaldar** [berlinjs/berlinjs.org#257]
##### Abstract

LoveBits is about writing code poems written in JavaScript, to show that code is more than just a functional language. It's about showing that code can even be used poetically, to tell stories.

Would tell a bit about how the project came to be, show pieces of code, and the interactive parts, when the code poems become interactive.

https://lovebits.bilebile.net/

###### Murat Kemaldar

@murimuffin5 (Twitter)
murat.kemaldar@outlook.com

Let me know what you think, looking forward for some feedback :)

**Comment by rmehner** [comment]
How long would this talk be?

**Comment by muratkemaldar** [comment]
I would say somewhere between 10 and 15 minutes.
