### ISSUE TITLE
Property-based testing: You won’t look at your tests the same way ever again

### ISSUE THREAD

**Issue by jstepien** [berlinjs/berlinjs.org#258]
##### Talk title

Property-based testing: You won’t look at your tests the same way ever again

##### Abstract

Property-based testing changes the way we look at our test suites. Instead of specifying test cases one after another, this advanced testing technique enables us to automatically generate a stream of inputs. Despite its potential, property-based testing still remains under the radar within the JavaScript community. Let’s try to uncover its strengths together.

The talk will discuss how property-based testing compares to traditional testing methods and demonstrate its principles with simple examples. In order to bust the myth of the inapplicability of property-based testing in a real-world setting we’ll bring up some use cases from industry. Finally, we’ll wander into the world of concurrency and the automation of race condition detection.

###### Your name

Jan Stępień

###### Means to get in touch with you

I'm at https://janstepien.com. On Twitter I'm [@janstepien](https://twitter.com/janstepien).

---

May 17th works! 😄

**Comment by rmehner** [comment]
Hey there,

for May we're already full, but we'll put you on the wait list. Our meetup is always on the third Thursday of the month. Is there any date that won't work for you? Or do you have a special preference?

**Comment by jstepien** [comment]
So far 3rd Thursdays in June and July look good to me 👍

**Comment by carolstran** [comment]
Sorry for the massive delay in response on this. But I was wondering if you would still be interested in giving this talk. And if so, how long would it be? 😊

**Comment by jstepien** [comment]
Hi Carolyn, no worries 😊. Yes, I'd be happy to. I shouldn't need more than 30 minutes. I can get it down to 20 if necessary.

**Comment by carolstran** [comment]
Hey hey @jstepien, another question for you 😅 Would you have any month(s) that would work especially well (or don't work) for you in 2019? We're on the third Thursday of each month.

**Comment by jstepien** [comment]
Let's see... Feb 21st could work, but I'd rather go for May 16th. I 
won't be able to make it in March and April. The rest of the year isn't 
clear yet. What would work best for you folks?

**Comment by carolstran** [comment]
Wow, thanks for your quick response! Really appreciate it. Looks like February is already full anyway, so it would be great if we could put you down for May 🙌

**Comment by jstepien** [comment]
Excellent, May 16th it is then. Can’t wait!

**Comment by carolstran** [comment]
Hey @jstepien, re: our conversation on Twitter I will move you back onto the waitlist. If you'd still be interested in giving your talk later this year, we'd love to have you! Just let me know what month works for you (and preferably in advance so we don't fill it up!)

**Comment by carolstran** [comment]
👋 Hey @jstepien! I made a note to check in with you about speaking in Q3. If you're available for either the August 15th or September 19th meetup, just let me know 😊

**Comment by jstepien** [comment]
Hey Carolyn! If the slot is still available, September 19th would be perfect.

**Comment by carolstran** [comment]
Hey @jstepien, sorry for the delay. Yes it's still available and I put you down! I'll check in again towards the end of August to confirm 😇

**Comment by carolstran** [comment]
👋 @jstepien 

Just wanted to check in to see if you're still available and want to present at our meetup on September 19? And if so, is the title and abstract you provided above correct?

If you could let me know either way by the end of the month, that'd be excellent 😁

**Comment by jstepien** [comment]
Hey Carolyn, yes, I'm available and looking forward to the meetup! The title and abstract are both correct. If the long title breaks the page layout, we can shorten it to _Let's Test That Real Quick_.

**Comment by carolstran** [comment]
Hey @jstepien  👋 I've added you to the website! https://berlinjs.org/ Now we're just waiting to add one more speaker before announcing.

**Comment by jstepien** [comment]
I've caught a cold and won't be able to be there tomorrow. Sorry!

Should we reschedule the talk? October 17th, November 21st and January 16th seem to work on my side. Let me know!

**Comment by rmehner** [comment]
@jstepien ugh, that sucks! Hope you'll get better soon! No worries about today, health is most important :)

We'll get back to you with date details once we know our plans.

**Comment by carolstran** [comment]
Hey hey @jstepien, I hope you're feeling better 💐 January would be great if that's alright with you! Just let us know.

**Comment by jstepien** [comment]
Yes, thanks, feeling much better. Perfect, January 16th it is. Looking forward to the meetup!

**Comment by carolstran** [comment]
Perfect! We have you down. We'll check in again closer to 🌟

**Comment by carolstran** [comment]
Hey hey @jstepien, just wanted to check in and see if you're still up for giving a talk at our meetup later this month (Thursday, January 16) 🎉 And if yes, then please let me know if you want to make any changes to your title/abstract before we add it to the website 🥂

**Comment by carolstran** [comment]
Friendly ping @jstepien because we'd like to announce the speakers this week (or if you can no longer speak then we'd need to find someone else) 😇

**Comment by jstepien** [comment]
Yes, I am and I'm looking forward to the meetup. The abstract and the 
title look good.

**Comment by carolstran** [comment]
Awesome! I'll update the website today!

**Comment by carolstran** [comment]
👋 @jstepien, we added your talk to [our website](https://berlinjs.org/) and [tweeted about it](https://twitter.com/berlinjs/status/1215196087532818433?s=20). Just so you know, @SaraVieira will be the only organizer at the meetup on Thursday, so please find her and check-in when you arrive 😊 

Co.up has an assortment of doggles, etc. - but if you need anything specific for your talk, please just let us know. Looking forward to finally having you on stage 🎉

**Comment by jstepien** [comment]
Thanks for having me! [The slides are online.](https://www.janstepien.com/lets-test-berlin-js/)

**Comment by carolstran** [comment]
👋 @jstepien, thank you again for giving a talk at our January meetup! I was sad to miss it, but it seems like it went very well and it was awesome to finally get you on stage. Always feel free to reach out if you have any feedback 😊
