### ISSUE TITLE
Web frontend security

### ISSUE THREAD

**Issue by ubenzer** [berlinjs/berlinjs.org#259]
Web frontend security
##### Abstract

An overview of frontend security related things that every web developer needs to know. It explains common attack methods and how to take precautions to prevent them. This presentation will explain what XSS, CSRF, Clickjacking are. It'll mention about preventative strategies and mention about CSP, HSTS, JWT, HTTP-Only Cookies on the way.

###### Your name
Umut Benzer

###### Means to get in touch with you
umut@benzer.me

**Comment by rmehner** [comment]
Hey there,

this is a super interesting topic and we'd be happy to have you soon. We've put you into our talk queue and will get back to you when we plan the next months. Are they are months that totally won't work for you that you already know of?

I'd like to ask you one thing tho: Can you please refrain from using images of war during your talk and in here? We have some attendees that actually come from war ridden regions and there's no need to confront them with these hard topics when they actually want to learn about web security. Thank you very much for your understanding :)

**Comment by ubenzer** [comment]
Hi @rmehner,
Thanks, looking forward to my turn. :-) I'll be careful about the images I use, promise. 

So far I don't have any time off planned.

**Comment by carolstran** [comment]
Hey @ubenzer! Sorry for the massive delay in response on this. I was wondering if you would still be interested in giving this talk. And if so, how long would it be? 😊

**Comment by carolstran** [comment]
One more question (if you're still interested), will this be your first time speaking or have you given talks before?

**Comment by ubenzer** [comment]
Hi @carolstran , no worries. 

I won't be able to do the talk anymore. I'll open another issue if I can manage to allocate some cycles to work on the talk again in the future.

Cheers,
Umut.

**Comment by carolstran** [comment]
Ahhh slightly bummed because this talk looked great, but if you ever want to give it (or another one) please reach out 🙌
