### ISSUE TITLE
How to hire frontend engineers

### ISSUE THREAD

**Issue by iwangu** [berlinjs/berlinjs.org#261]
##### Talk title

How to hire frontend engineers

##### Abstract

When people don’t get job offers, they think, they are just not good enough. After working for three years in recruiting, I can assure you that often rejections happen due to randomness that you wouldn't believe is possible. 
In this talk, I tell three stories where great applicants were rejected for reasons that had nothing to do with their engineering performance or cultural-fit. Based on that, I give antidotes to both job-seekers and hiring managers how to avoid these traps.
 
###### Your name

Iwan Gulenko

###### Means to get in touch with you

E-mail: iwan@coderfit.com
Twitter: @iwangulenko 

Similar talk that I gave: https://www.youtube.com/watch?v=u6PTaTDHUG4

**Comment by carolstran** [comment]
Hey @iwangu! I was wondering if you would still be interested in giving this talk. And if so, how long would it be?

I can't guarantee anything at the moment, but we're trying to figure out what we're working with in 2019 and a better way to structure our proposal process in the future 😊

**Comment by iwangu** [comment]
Thanks for asking! Gladly in a few months if that's ok? Cheers!

**Comment by carolstran** [comment]
Unfortunately I can't guarantee anything at the moment, but knowing how long you'd like to speak for would be useful so that we can better plan 😁 Anything between 5-25 is ok by us.

**Comment by iwangu** [comment]
25 i guess. maybe archive this for now and i resubmit later during the year?

**Comment by carolstran** [comment]
Yeah that works! I'll close it and feel free to reopen or resubmit when you want 😊
