### ISSUE TITLE
Functional Programming + React = ❤️

### ISSUE THREAD

**Issue by herrherrmann** [berlinjs/berlinjs.org#262]
##### Talk title
Functional Programming + React = ❤️

##### Abstract
Everyone has heard about Functional Programming sooner or later but not many people have seen it in action. I'd like to show you some of our real React code examples that leverage the power of FP to become readable and reusable and make you a better programmer in general!

###### Your name
Sebastian Herrmann

###### Means to get in touch with you
Twitter: [@herrherrmann](https://twitter.com/herrherrmann)
_(Feel free to include it on the website!)_

**Comment by rmehner** [comment]
Hey hey,

that sounds super interesting, also 👍 on that emoji use in the talk title ;)

We're in the process of confirming for July and it looks like we're already full. Do you have a preferred month (except September, which is already full as well).

**Comment by herrherrmann** [comment]
Hello there,
I'm happy you find the topic interesting!

July and August are quite busy for me, so let's aim for October?

**Comment by rmehner** [comment]
Alright, put you down for October. Will get back to you weeks before October to get the final confirmation :) Have a great summer until then, hope you find some time to enjoy it in all your busy days.

**Comment by rmehner** [comment]
@herrherrmann does October still work for you?

**Comment by herrherrmann** [comment]
@rmehner Yes! It'd be October 18th, correct?

**Comment by rmehner** [comment]
@herrherrmann yup. And great to hear, will put you on the website ASAP then :)
