### ISSUE TITLE
Side effects unit testing for ES6 modules

### ISSUE THREAD

**Issue by peter-leonov** [berlinjs/berlinjs.org#263]
##### Talk title

Testing ES6 modules with Introscope

##### Abstract

Testing ES6 modules can be tuff, esp. if the module has small public API but rich internals. We in my team at Zalando developed a babel plugin (called Introscope) helping to look inside any module turning it into a factory function. This helped us develop some cool techniques for more or less robust side effects based testing with mocks, spies and Jest snapshots.

###### Your name

Peter Leonov

###### Means to get in touch with you

Here is my mostly abandoned Twitter: https://twitter.com/peterleonov
And just in case Github follows Skype: gojpeg@gmail.com

**Comment by rmehner** [comment]
That's a super interesting talk. We have some talks in queue for July, but none confirmed yet. I'll get back to you once we have that clear.

If July wouldn't work, do you have any preferences when it comes to the month? (except September, which is full already)

**Comment by peter-leonov** [comment]
Thanks ☺️

July sounds good 👍, am not sure about August though because of a vacation.

**Comment by rmehner** [comment]
July is already full now (we had to wait for some confirmations). If August does not work, we always can move you to another month, just tell us your preferences :)

**Comment by peter-leonov** [comment]
It's a bit pity that there is no time for a lightning talk in July. Could you then please tell me when in August shell we try to plan my talk?

**Comment by rmehner** [comment]
The meetup is always on the third Thursday of the month, that is August 16th. Will this work for you?

**Comment by peter-leonov** [comment]
Looks promising, I'm going to have a vacation in last days. Shell I book the place somehow officially? 😂

**Comment by peter-leonov** [comment]
Hey, @rmehner! Is it going to happen on 16th?

**Comment by rmehner** [comment]
Hey Peter, planned to get back earlier to you, but then had to travel and this got lost. Sorry. Also another slight issue presented itself: We've accidentally double booked the third slot for August.

It's you and a talk about accessible charts that is also super interesting. So our options would be either:

1. Have four talks. Which might be a bit of a challenge, given the current weather ;)
2. Move one of you to October. There's two talks set for October already, one of it is #262.

Do you have a preference? And sorry again, the heat melted my brain and my ability to properly schedule things :) A drink of your choice is on me to make up for it.

**Comment by peter-leonov** [comment]
Thanks for a quick answer! It's perfectly fine to shock the world in October with my super module. In case it gets too hot: https://kaltekarte.berlin :)

**Comment by rmehner** [comment]
> It's perfectly fine to shock the world in October with my super module.

Haha, can't wait :) Scheduled you in for October. Thanks for being flexible! Drink is still on me :)

> https://kaltekarte.berlin

That's gold. Forwarded it to a couple of friends. Thanks!

**Comment by peter-leonov** [comment]
Hey there, Robin!

Poking you just to check if I still shell expect to to talk on the October meetup.

**Comment by rmehner** [comment]
Hey Peter,

yes, you're still planned for October. There's one spot that freed up for September, so if you'd like that spot, I'm happy to move you to that :) Your choice!

**Comment by peter-leonov** [comment]
Yes, sure! September is better :)

**Comment by rmehner** [comment]
Great, will put you on the website asap (I'm travelling today, might take some time)

**Comment by rmehner** [comment]
@peter-leonov You're on the website now and we'll tweet / do the announcement thing very soon :) I'll close this for now and am very much looking forward to seeing you next week!

**Comment by peter-leonov** [comment]
Hi @rmehner,

sorry for me being sick on the date of the meetup, being a bit stupid during the talk too and also for running away so fast. Shit happens to me occasionally :) Thanks for the opportunity to talk to smart people!

P. S. Thanks for inviting the Michaela Lehr with her great talk on technology. I would have missed this treasure otherwise!

**Comment by rmehner** [comment]
👋 @peter-leonov, all good and thank you for your talk again (and that shirt ;-))

Hope to see you around.
