### ISSUE TITLE
Talk proposal: A sneak peek at BinaryAST

### ISSUE THREAD

**Issue by linclark** [berlinjs/berlinjs.org#264]
Hey y'all! It looks like I may be in Berlin in time for the August meet up. 🙌🏻 Will it be on August 16th?

##### Talk title

A sneak peek at BinaryAST

##### Abstract

Preparing this set of slides for July's TC39, so will fill in an abstract once that's done.

###### Your name

Lin Clark

###### Means to get in touch with you

https://twitter.com/linclark

**Comment by rmehner** [comment]
OHAI @linclark, great to see/read you again :)

> Will it be on August 16th?

Yes, indeed. I'll put down a note into our Trello for August. Have a great weekend!

**Comment by rmehner** [comment]
@linclark *ping* We've reserved you a spot, does this still work for you?

**Comment by linclark** [comment]
@rmehner Thanks for checking in. Unfortunately we ended up not presenting about this at the last TC39, so I won't have this presentation ready. I could do a 15 minute presentation on WebAssembly ES module integration if that would be of interest, or happy to free the slot for someone else.

**Comment by rmehner** [comment]
> could do a 15 minute presentation on WebAssembly ES module integration if that would be of interest

That sounds good. Would love to have you on stage, given that you're usually not in town.

15 minutes also sounds good, it's gonna be a warm summer evening anyway :)

**Comment by linclark** [comment]
Awesome, it will be great to see you all again! 🙌🏻

**Comment by rmehner** [comment]
Hey there, I've put on a stub for your talk onto our website. Can you please give me a sentence or two as abstract? Doesn't have to be long, just some more info on what you're going to present :) Thanks and I hope you're prepared for a very summer Berlin!

**Comment by linclark** [comment]
Apologies for not getting this to you sooner!

> Currently, WebAssembly modules and JavaScript modules don't play together... but that's changing. With ES module integration, JavaScript modules and WebAssembly modules will live in the same module graph. In this talk, I'll explain how this will work and where we are in the process of making it happen.

**Comment by rmehner** [comment]
All good, thanks for providing the description, just added it to the website. See you Thursday!

**Comment by linclark** [comment]
@rmehner FYI, it looks like my flights are getting messed up by weather, so I may not get to Berlin in time
