### ISSUE TITLE
Talk proposal: A11Y IRL (Accessibility in real life)

### ISSUE THREAD

**Issue by vorillaz** [berlinjs/berlinjs.org#265]
##### Abstract

The year is 2018, and accessibility is not a buzzword anymore. It’s now imperative that information is readily available to everyone, regardless of their disability or financial status. 
In this talk, you’ll find out how to create accessible real-life objects, using run-of-the-mill JavaScript and the basic principles of Internet of Things.

###### Your name
Theodore Vorillas

###### Means to get in touch with you

You may catch up with me via twitter [https://twitter.com/vorillas](https://twitter.com/vorillas) or via email theodorevorillas@gmail.com

**Comment by rmehner** [comment]
b3cbf6e790da0423166f4d1a8136511137d8e884
