### ISSUE TITLE
Making Weird Physical Art + Games With Cross-Platform JavaScript

### ISSUE THREAD

**Issue by lazerwalker** [berlinjs/berlinjs.org#266]
Hey! I'll be giving a variation of this talk at a conference in the US in September. I'd love the opportunity to give it a test run in August if y'all are interested :)

##### Talk title

Making Weird Physical Art + Games With Cross-Platform JavaScript

##### Abstract

How can we use JS to make weird games and interactive art installations? “Hello, Operator!” (https://lazerwalker.com/hellooperator) is a game made for a physical telephone switchboard from 1927. I'll talk about why prototyping both on- and off-hardware matters for projects like this, how I used JS to build a cross-platform game engine that runs anywhere from a CLI to an iPad to 100-year-old hardware, and at a high level how anyone with JS skills can get started with hardware.

###### Your name

Mike Lazer-Walker

###### Means to get in touch with you

https://twitter.com/lazerwalker
https://lazerwalker.com

**Comment by lazerwalker** [comment]
Hey! Just wanted to bump this. Hope this doesn't come across as pushy, but if y'all would like me to speak I'd like to know so I can be sure to be ready in two weeks :)

**Comment by rmehner** [comment]
Hey @lazerwalker, this talk sounds super interesting and we'd love to have it. I love myself some cool & fun JS projects.

However, August is fully booked out (in fact I accidentally double booked the third slot). October is a bit in limbo (as one of the people who double booked might move there), so the earliest would be November. Would that work for you? If October frees up or someone cancels, I'd also get in touch with you again. Does this work for you?

**Comment by lazerwalker** [comment]
Sounds good! Do let me know about October, as there's a slim chance I won't be around the third week of November.

**Comment by rmehner** [comment]
hey @lazerwalker, due to some shifts in schedule a spot for September freed up. Would you be up to take that, as your talk would fit perfectly with the other two talks :)

Lemme know if that works for you and if not, don't worry.

**Comment by lazerwalker** [comment]
Hey @rmehner! Thanks for the offer! Afraid I'll be traveling in September, though, so we'll have to stick with November.

**Comment by rmehner** [comment]
@lazerwalker all good, scheduled you in for November then :)

**Comment by carolstran** [comment]
🛎 @lazerwalker - Just sent you a Twitter DM via the BerlinJS account. If you could check it and either answer it there (or here), that'd be amazing!

**Comment by carolstran** [comment]
👋 Closing this issue now. Thanks again @lazerwalker for the amazing talk!
