### ISSUE TITLE
[Talk] Enforceable environment variable contracts at runtime

### ISSUE THREAD

**Issue by Incognito** [berlinjs/berlinjs.org#267]
##### Abstract

A library that enforces a schema for enviornment variables that is enforced at run time (and also compile-time if using TypeScript). Able to use rich-types such as enforcing high-entropy passwords or real URLs, as well as grouping common envvars together.

https://github.com/freight-hub/TypedEnv

##### Your name

Brian Graham

##### Means to get in touch with you

I'm on GitHub more than social media.

**Comment by rmehner** [comment]
Hey there,

do you have any preference when it comes to months? Next three months are fully booked, but we might have some spots left for November and December.

**Comment by Incognito** [comment]
November would work.

**Comment by Incognito** [comment]
@rmehner when should I expect to get a confirmation or rejection?

**Comment by rmehner** [comment]
@Incognito sorry, forgot to get back to you. You're actually planned in for November :)

**Comment by carolstran** [comment]
Hey @Incognito, quick question for you. 

We currently have you scheduled for the November meetup, but we wanted to ask if you're available at another date, as we have a speaker that can only present in November as she's leaving Berlin. So if we could reschedule your talk (maybe for January 2019?), it would be really helpful, but only if it works for you. 

Just let us know. Thank you!

**Comment by Incognito** [comment]
January will be busy for me (and most other people I'm sure, but it also contains my Birthday). Which day will it likely fall on? Around the 15th?

**Comment by carolstran** [comment]
Yeah totally understand, @Incognito. It would be on January 17th, but again, no pressure to reschedule - it would be only if it works for you.

**Comment by Incognito** [comment]
@carolstran great, let's book the 17th of January. Thanks!

**Comment by carolstran** [comment]
No thank you 🎉 Really, really appreciate your flexibility 🙏 @Incognito

**Comment by carolstran** [comment]
Hey @Incognito, just wanted to confirm if you're still able to speak next week 😊 We'd like to announce the speakers this week. Also, do you know how long your talk will be?

**Comment by Incognito** [comment]
Yep, you can include me for January.

The talk can be anywhere from 5 minutes to 30 minutes, depends on how much detail you want. I think 20 is fine for a non-junior audience.

cc @artfwo want to join, maybe bring any examples or stories of how it was used?

**Comment by artfwo** [comment]
@Incognito will happily join and notify the team here as well.

**Comment by carolstran** [comment]
@Incognito Great! It would be great to keep it junior-friendly, but if that is not possible, maybe just point it out at the beginning of your talk. 

For January, there will only be two speakers so we're more flexible on the time - but it would be great to keep it around or under 30 minutes.

Thanks again and looking forward to meeting you on Thursday!

**Comment by Incognito** [comment]
The Meetup was great, thanks!

**Comment by rmehner** [comment]
@Incognito Thanks for your great talk :)

**Comment by carolstran** [comment]
Yes so excellent @Incognito! Also if there are any other links/resources/etc that you want us to tweet out, just let us know 😊
