### ISSUE TITLE
Talk Proposal: Building high performance native mobile apps with Titanium

### ISSUE THREAD

**Issue by Topener** [berlinjs/berlinjs.org#269]
##### Abstract

A common misconception with cross platform tools like Titanium (or React Native) is that apps built using those technologies are less performant than native apps. And while this is often the case, the cause is rarely the technology, but how it is used. 

But how do you achieve high performance for both iOS and Android? This talk will dive into common pitfalls which slow down the app or make it feel sloppy, and obviously how to avoid them and structure your Titanium app so you can avoid this.

###### Your name
Rene Pot

###### Means to get in touch with you
Twitter: [@Wraldpyk](https://twitter.com/wraldpyk)
Email: rene@topener.nl
BerlinJS Slack: Wraldpyk

ps: I'm available for December and later.

**Comment by rmehner** [comment]
Thank you :) You're already on our waitlist, we won't have a meetup on December, but will keep you posted for January :)

**Comment by carolstran** [comment]
Hey @Topener! I was wondering if you would still be interested in giving this talk. And if so, how long would it be? 😊

**Comment by carolstran** [comment]
One more question, will this be your first time speaking or have you given talks before?

**Comment by Topener** [comment]
Hi! Apologies for the late reply, missed the notification. I am still up to give this talk, or a similar talk surrounding cross platform appdev. 
I'm speaking quite a lot around Europe. You can find my history at [my site](https://renepot.net/speaking/)

**Comment by carolstran** [comment]
Sounds good! How long would your talk be? Anything between 5-25 minutes is fine by us, but knowing roughly how long helps us with planning 😊

**Comment by Topener** [comment]
20-25 minutes is my preferred length! Which month would a slot open up?

**Comment by carolstran** [comment]
Great, thanks for the info! Honestly, I'm not sure yet because I'm still gathering all of the information from the other proposals. We'll keep you posted though 😇

**Comment by carolstran** [comment]
Actually, would you have any month(s) that would work especially well for you? We're on the third Thursday of each month.

**Comment by Topener** [comment]
I'm currently in discussions on March for somewhere else, so April (or later) would probably work best for me.

**Comment by carolstran** [comment]
Great! We could actually put you down for April now and then check in again in March or so. Would that work for you?

**Comment by Topener** [comment]
Hi! If you can put me in a slot now already then I'm happy to confirm I'll be coming straight away. Can you email me a confirmation? Then I can get my trip booked ;)

**Comment by carolstran** [comment]
Yes we can confirm! @rmehner will send you a ✨very official ✨ email.

**Comment by carolstran** [comment]
Hey hey @Topener! We updated the website with the info for the April meetup. Can you check it out and let us know if anything is wrong/you'd like to change something? https://berlinjs.org/

We're aiming to announce the meetup later this week 🎉

**Comment by Topener** [comment]
All good! Thanks for that :) Cheers

**Comment by carolstran** [comment]
Closing this as you already delivered your talk. Thanks again! 👏
