### ISSUE TITLE
Talk proposal: Feature Driven Architecture

### ISSUE THREAD

**Issue by kof** [berlinjs/berlinjs.org#271]
##### Talk title

Feature Driven Architecture

##### Abstract

Large applications cannot be structured the same way as small applications. Many good decisions you make for a small application suddenly become bad once it grows in code and organization size. Let me walk you through a number of challenges and good decisions for scalable applications.

###### Your name

Oleg Isonen

###### Means to get in touch with you

https://twitter.com/oleg008
oleg008@gmail.com

P.S. This is a dry run of a talk I will be doing at reactdayberlin, so I hope to get some feedback and improve it.

**Comment by kof** [comment]
Oh, too bad this one wasn't accepted for 15th nov, I needed the talk as a preparation for the conference.

**Comment by rmehner** [comment]
@kof sorry, November lineup was already full before we got this submission from you :) Would you be up to give it somewhen next year?

**Comment by kof** [comment]
Didn't realize that, lets see next year, because it will depend on a feedback I get to this presentation. Good to see so many presentations get submitted!
