### ISSUE TITLE
Talk Proposal: Applying visual automata-based programming to user interfaces

### ISSUE THREAD

**Issue by lukaszmakuch** [berlinjs/berlinjs.org#275]
##### Abstract

1. What does it mean that user interfaces are stateful and how can we use state machines to decompose them?
1. A brief introduction to visual automata-based programming in functional JavaScript.
1. An overview of the codebase of a wizard

- The talk is around 20 minutes long.
- I gave a very similar talk a year ago at Angular Bolivia.
- All examples are written in Rosmaro.

###### Your name

Łukasz Makuch

###### Means to get in touch with you

Twitter: [@zopsesen](https://twitter.com/zopsesen)

**Comment by carolstran** [comment]
Hey @lukaszmakuch, thanks for submitting a talk 😊I've added it to our queue and we'll get back to you when we have a better idea of when it would fit in.

**Comment by carolstran** [comment]
Actually one question @lukaszmakuch, are you based in Berlin?

**Comment by lukaszmakuch** [comment]
Hi @carolstran ! Thanks for your answer. :) Yes, I'm based in Berlin.

**Comment by carolstran** [comment]
👋 @lukaszmakuch, quick question for you. Is there any chance that you'd be open to delivering a 5-10 minute version of your talk?

If not, no worries - we can keep you on the regular waitlist. Just trying to think of ways to get more people on our stage before the end of 2019  🤔💡 ⚡️ 🚀

**Comment by lukaszmakuch** [comment]
Hi @carolstran! 👋 That's an interesting challenge! 😄 I think I can prepare a 10 minutes long version. 👍 Simply instead of going into the details of some wizard 🧙‍♂️, I can explain something a lot simpler, like a button 🔘. Let me know what do you think about this idea. 🙂

**Comment by carolstran** [comment]
That sounds great actually! Ok I'm going to label this issue with a ⚡️ 

Once I hear back from everyone else, then we can talk about dates 🙌

**Comment by carolstran** [comment]
Hey @lukaszmakuch, turns out we have an opening for our upcoming July meetup on Thursday, July 18. Any chance you're available and would like to give a 10-15 minute version of your talk? If it's too last minute, no stress! We can also find another date, just wanted to check and see 😇

**Comment by lukaszmakuch** [comment]
Hey @carolstran, I'd like to confirm that I'm available on July 18 to give a short version of this talk. 😃

**Comment by carolstran** [comment]
That's amazing, thank you! We'll announce the speakers later this week 🚀

**Comment by carolstran** [comment]
Hey @lukaszmakuch! Here's the updated website, let us know if you'd like us to change anything about your info or abstract: https://berlinjs.org/

We'll be announcing speakers on Twitter tomorrow 🛰

**Comment by lukaszmakuch** [comment]
Hello @carolstran, thank you for the update! Could you please trim the description a bit, to remove the mention of the wizard app?
My suggestion would be:
>  What does it mean that user interfaces are stateful and how can we use state machines to decompose them? This talk will be a brief introduction to visual automata-based programming in functional JavaScript. 

Sorry for the confusion, it's just that in the lightning talk format I won't be able to cover that code. I hope it's not too late to ask. Thanks! :)

**Comment by carolstran** [comment]
Not too late at all, that's why I wanted to send it beforehand 😁 I'll adjust and then tweet the announcement 🎉 Thank you for such a prompt response!

**Comment by carolstran** [comment]
Also just so you know, one of the other speakers dropped so if your talk runs over 10 minutes that's ok too 😊

**Comment by carolstran** [comment]
Hey hey @lukaszmakuch, really looking forward to meeting you and hearing your talk 🎉 

FYI we added a fourth speaker for tonight so here is the tentative schedule...

⚡️ Jan-Niklas
🎤 Liam
- break - 
⚡️ You!
🎤 Robin

I'll be the only organizer there tonight, so just find me before or during the break and we can do a quick tech check 😊

**Comment by carolstran** [comment]
Thanks again @lukaszmakuch, tonight was excellent 💕  Closing this issue now 😁
