### ISSUE TITLE
Talk proposal: You’re joining a project

### ISSUE THREAD

**Issue by omaiboroda** [berlinjs/berlinjs.org#276]
##### Talk title
You’re joining a project

##### Abstract

If you’re starting on new (for you) project it’s alway nice to enable “GPS” and see what the project is and how “healthy” it is.
In the talk we’ll go through some tips which can give you insights of the project's state:
* **How big is it?** Number of `Lines of Code` and comparison to popular libs/projects;
* **How old is it?** Date of first commit;
* **How complex is it?** `Code complexity` metric;
* **Who was contributing in it?** I.E. `Github insights`;
* **Is it performant/accessible/seo-friendly?** With Google `Lighthouse`;
* **Is it easy to release?** `Build time` of a project;
* **Are the dependencies up to date?** With `npm outdated`;

These and other metrics will give you a knowledge about the project you’ve joined and turn on the GPS, so you can navigate the project to success.

###### Your name

Oles Maiboroda

###### Means to get in touch with you

[oles.maiboroda@gmail.com](mailto:oles.maiboroda@gmail.com)

**Comment by carolstran** [comment]
Hey @omaiboroda 👋 Weird to talk to you over a non-Blacklane repo, but just wanted to let you know that I sent your proposals to the other organizers. We will take a look and let you know which topic fits best 😊

**Comment by carolstran** [comment]
Hey again 👋 After speaking with the other organizers, we'd love to have your present your other talk proposal - `What should I use - Static pages, SSR or SPA? Maybe Prerendering?`. 

Both proposals are interesting, but (in the words of @rmehner): the second one is really neat, as this answers a lot of questions that people have around SPAs and best practices.

So if it's alright with you @omaiboroda, I would close this issue and move forward with your other one. Wdyt?

**Comment by omaiboroda** [comment]
Sounds good to me 👍 
Thanks, @carolstran !

**Comment by carolstran** [comment]
Great then I'll close this issue and write back on the other ttyl ✌️
