### ISSUE TITLE
Talk proposal: "What should I use - Static pages, SSR or SPA? Maybe Prerendering?"

### ISSUE THREAD

**Issue by omaiboroda** [berlinjs/berlinjs.org#277]
##### Talk title

What should I use - Static pages, SSR or SPA? Maybe Prerendering?

##### Abstract

Nowadays there are different approaches on how to ship frontend to a user - 
* Static pages export;
* Prerendering;
* Server Side Rendering;
* Single Page Application;

In the talk, we can review them, discuss pros & cons (_build time, release time, performance, cost_) and match those approaches to popular frontend libraries.

###### Your name

Oles Maiboroda

###### Means to get in touch with you

oles.maiboroda@gmail.com

**Comment by carolstran** [comment]
Hey @omaiboroda 👋 As mentioned on the other issue, we'd love to have you present this talk. A couple of questions: Do you know how long the talk will be? Anything between 5-25 minutes is fine by us. Also, do you have any months that work particularly well for you? We're on the third Thursday of every month.

**Comment by omaiboroda** [comment]
Hi!
The topic is quite big, but I'd like to fit in 20 minutes. May / July works for me, is any of those work for you?

**Comment by carolstran** [comment]
May works! I'll mark it as confirmed and just let us know if something comes up between now and then 😊

**Comment by omaiboroda** [comment]
Hi folks, unfortunately, due to work, I'll not be able to do a talk. My apologies, but we'd need to postpone it to better days, I'll get to you as soon as I'll be ready.
Sorry for the short notice.

**Comment by rmehner** [comment]
@omaiboroda that's a pity. Hope work clears up soon, let us know when you know what date would work for you. Best of luck!

**Comment by carolstran** [comment]
@omaiboroda Thanks for letting us know! Moved you back to the waitlist. When you have a better idea of when you'd want to give it - just reach out 😊

**Comment by carolstran** [comment]
👋 @omaiboroda, do you know if you'll be able (or want) to present in 2019? Just want to make sure we save a spot for you 😇

**Comment by carolstran** [comment]
Friendly ping @omaiboroda  🛎

**Comment by omaiboroda** [comment]
Hey, @carolstran, sorry, was on a vacation 🗽
Yes, I still have the interest to do a talk on BerlinJS, although I'll submit it once I'll be ready with the content (probably it would be another topic ;) ). We can close this issue for now.

**Comment by carolstran** [comment]
Oh yeah!!! Sorry completely forgot, hope you enjoyed my homeland 🇺🇸 

Sounds good, I'll close this for now and really looking forward to seeing what you end up submitting!
