### ISSUE TITLE
Talk proposal: "How to connect 1980 and 2019 with a Chrome extension and Chrome Native Messaging"

### ISSUE THREAD

**Issue by matthieukern** [berlinjs/berlinjs.org#278]
##### Talk title

How to connect 1980 and 2019 with a Chrome extension and Chrome Native Messaging

##### Abstract

At Doctolib, we need to interface with different kinds of softwares, from SAAS platforms to native softwares developed in 1980. Almost none of these are meant to allow communication with external tools. We've setup an API using a Chrome extension and a nodejs binary deployed on the machines of our clients to connect with these softwares.

During this talk, we'll speak about how to create a Chrome extension allowing to do such actions. We'll also talk about the deployment of a binary written in Javascript and embedding a Node.JS runtime with PKG to communicate using Chrome Native Messaging with the Chrome extension.

This is a 20min talk in two complementary parts (Chrome extension/native binary) with two speakers.

###### Your name

Matthieu Kern (@matthieukern)
Quentin Ménoret (@qmenoret)

###### Means to get in touch with you

Our emails:
- matthieu.kern@doctolib.com
- quentin.menoret@doctolib.com

**Comment by carolstran** [comment]
Hey @matthieukern and @qmenoret 👋 Thanks for submitting a talk! One question before we continue, are either (or both) of you a first-time speaker?

**Comment by matthieukern** [comment]
Hi @carolstran it's the first time we speak at Berlin, but we both did some talks in France in the past :)

**Comment by carolstran** [comment]
Hey @matthieukern, thanks for the info! I've added you to our waitlist and will let you know when we have a better idea of when we'd be able to get you into the lineup 😊

**Comment by carolstran** [comment]
👋 @matthieukern and @qmenoret, quick question for you. Is there any chance that you two be open to delivering a 5-10 minute version of your talk?

If not, no worries - we can keep you on the regular waitlist. Just trying to think of ways to get more people on our stage before the end of 2019  🤔💡 ⚡️ 🚀

**Comment by qmenoret** [comment]
Hello @carolstran, it's going to be complex to reduce the length of the talks. It's actually two talks of ~10 minutes, but they have to be one after the other since the second is based on the first one.

**Comment by carolstran** [comment]
Ooooh good to know. Ok waiting for some other responses and I'll keep y'all posted 😁

**Comment by carolstran** [comment]
Hey again 👋 Would you both be available to give the full version of the talk at our November meetup? It's on Thursday, November 21.

**Comment by matthieukern** [comment]
Hey @carolstran! Sure, we're available 🙂

**Comment by carolstran** [comment]
Amazing! Let's plan for that then and I'll check in with you both in a couple months 😊

**Comment by carolstran** [comment]
Hey hey @matthieukern and @qmenoret, just wanted to check in and see if you're still up for giving a talk at our meetup later this month (November 21) 🍰 And if yes, then please let me know by the end of the week if you want to make any changes to your title/abstract before we add it to the website! 

We're aiming to announce the lineup next week 😊

**Comment by matthieukern** [comment]
Hey @carolstran! We're still in for this talk 🙂 I just corrected a typo in the abstract, for the rest it's fine for us!

**Comment by carolstran** [comment]
Sweeeeeet looking forward to it then!

**Comment by carolstran** [comment]
Sorry last question: Do either of you have Twitter?

**Comment by matthieukern** [comment]
I have it (https://twitter.com/matthieukern), but haven't used it in ages… Quentin as well (https://twitter.com/QuentinMenoret) but same extensive usage

**Comment by carolstran** [comment]
Thank you again for speaking! I heard it went very well and I hope you both enjoyed it 💃 Closing this issue now 👋

**Comment by rmehner** [comment]
@matthieukern @qmenoret do you happen to have the current slides at hand? I found https://de.slideshare.net/MatthieuKern1/how-to-connect-1980-and-2018 but can't tell if you've updated them :)
