### ISSUE TITLE
Talk Proposal: Modular Synthesis in the Browser

### ISSUE THREAD

**Issue by rain-sk** [berlinjs/berlinjs.org#279]
##### Talk title

Replacing Redux with React's Hooks and Context APIs

##### Abstract

The most common reasons for using Redux are:
1) Sharing state with deeply-nested components while containing global state in a single place.
2) Giving deeply-nested components the ability to apply "actions" to the global state.

Now that Hooks and Context APIs are stable, we can accomplish this without Redux.

Introducing `use-flux`: a light-weight package for declaring and consuming global stores using a flux-like pattern of state transformations.

This talk isn't really about convincing you to use `use-flux`, but it _is_ about demonstrating the structure of a React Hooks package!

###### Your name

Spencer Rudnick

###### Means to get in touch with you

✉️ spencerudnick@gmail.com
🐦 @spencerfordES
⚛️ https://spencerudnick.github.io/use-flux

**Comment by carolstran** [comment]
Hey @spencerudnick 👋 Thanks for submitting! Got you on the waitlist. 

A couple questions in the meantime: I noticed your GitHub profile says you're based in Chicago. Is that correct? And if so, would you need travel and/or accommodation covered? And finally, are you a first-time speaker?

**Comment by rain-sk** [comment]
Hi! I'm actually based in Berlin now, need to update my profile 💯 So no need for travel accommodations.

I would be a first time speaker, however.

**Comment by carolstran** [comment]
👋 @spencerudnick, ugh sorry for my last response!

We'd love to have you speak. Here are the meetup dates for the rest of the year (except July because we already have a full lineup). Let me know if any of these work for you 😊 

August 15
September 19
October 17
November 21

**Comment by rain-sk** [comment]
Hi @carolstran,

I could present in September or October! Let me know which you prefer.

**Comment by carolstran** [comment]
October would be perfect for us if that's ok 😊

**Comment by rain-sk** [comment]
October works. Let's do it!

**Comment by carolstran** [comment]
Got you down! I'll check in again closer to, but just let us know if anything on your side changes 🎉

**Comment by carolstran** [comment]
Hey hey @spencerudnick, just wanted to check in and see if you're still up for giving a talk at our meetup later this month (October 17) 👻  And if yes, then please let me know if you want to make any changes to your title/abstract before we add it to the website 🎃

**Comment by rain-sk** [comment]
Hi @carolstran! I am still interested in giving a talk but I'm wondering if I can change the subject. If not no worries :)

Instead of being specific to React APIs and Redux, I'd be interested in presenting Synth Kitchen (https://synth.kitchen), as well as some of the code and thinking behind it.

*Talk Title*

Modular Synthesis in the Browser


*Abstract*

Synth Kitchen is a modular synthesis environment powered by React, the Web Audio API, and the Web MIDI API. In this talk I'll demo some synth patches, review the code architecture, and discuss the plans for future development of Synth Kitchen.

**Comment by carolstran** [comment]
Of course you can change, no problem! And selfishly I'm much more interested in this topic 👹 🎉 

Once the other speakers confirm, I'll add you to the website, announce it on Twitter, etc. Aiming for next week 😁

**Comment by carolstran** [comment]
Great, so I've updated the website - just let me know if we should change anything: https://berlinjs.org/ Planning to announce on Twitter tomorrow!

**Comment by carolstran** [comment]
👋 @spencerudnick, thank you again for giving a talk at our October meetup! From what I heard it went really, really well 💙 I'll close the issue now, but always feel free to reach out 😊
