### ISSUE TITLE
Talk proposal: Yet another talk about async/await and promises

### ISSUE THREAD

**Issue by viniciuskneves** [berlinjs/berlinjs.org#280]
##### Abstract

Based on this blog post: https://dev.to/viniciuskneves/yet-another-post-about-asyncawait-and-promises-49gg

Walk step by step on how Promises and asyc/await are connected with an example from a real question asked on Slack.

###### Your name

Vinicius Kiatkoski Neves

###### Means to get in touch with you

BerlinJS Slack: viniciuskneves

**Comment by carolstran** [comment]
Hey @viniciuskneves 👋 Thanks for submitting! Got you on the waitlist. Are you a first-time speaker? Based on your title you might know that we recently had a talk on a similar subject. This might not be an issue if you present later in the year, but just FYI 😊

**Comment by viniciuskneves** [comment]
Hey @carolstran 

It is my first time in English to be honest. I've had some experiences before back in Brazil (Portuguese).

Yeah, I was there as well and it is one of the motivations to talk about it again as people frequently get confused about this subject.

So no problem presenting it later on. Just ping me again when it fits best!

**Comment by carolstran** [comment]
👋 @viniciuskneves, quick question for you. Is there any chance that you'd be open to delivering a 5-10 minute version of your talk?

If not, no worries - we can keep you on the regular waitlist. Just trying to think of ways to get more people on our stage before the end of 2019  🤔💡 ⚡️ 🚀

**Comment by carolstran** [comment]
Closing this one in favor of #288 😁
