### ISSUE TITLE
How I accidentally fall in love with testing!

### ISSUE THREAD

**Issue by yatki** [berlinjs/berlinjs.org#283]
Speaker: Mehmet Yatki
Twitter: https://twitter.com/mehmatrix
Github: https://github.com/yatki

## Title of the talk:
How I accidentally fall in love with testing!

## Abstract: 
It may sound weird but I **love** testing, and I think testing has started to like me back. This is the story of my journey of accidentally becoming a real test advocate. We will explore the reasons why testing can be painful, and how to remedy them and also cover test types, test doubles and useful metrics

## Motivation

This talk is mainly aimed for junior and mid-level developers.

My motivation behind this talk to share how I learned to listen to my tests, what did they say about my code and how they eventually made me a better developer.

I'd like to talk about real testing challenges and the possible ways to solve them with giving code samples. 

I hope at the end of this talk, developers who are reluctant to write tests, will get excited, be more confident and have fun while testing their apps.

## Draft Agenda:
3~5 minutes: my observations and findings on reasons that makes testing painful and how can we fix those reasons.
10 minutes: covering testing terminologies like test types, test doubles, useful metrics. 
5 minutes: tools and the ecosystem that we currently have. 
5 minutes: real world code examples, tips and tricks.

Duration: ~25 mins.

**Comment by yatki** [comment]
Hey @carolstran. Sorry for the late reply. As i said before, that's totally fine. Looking forward to get a slot. 😄 

I see that next event is on June 20th, so do you have an estimation when I can hear from you again? And how are you gonna proceed with the proposals in this repo? Is it again vote based, or ordering by application date, or some other way?

**Comment by carolstran** [comment]
Hey @yatki, super sorry for my delay. We've moved you to the regular waitlist, so it's more of a matter of time. However, I was wondering if you'd be willing to present the 10-minute version of your talk?

If not, no worries - just trying to think of ways to get more people on our stage before the end of 2019  🤔💡 ⚡️ 🚀

**Comment by yatki** [comment]
Hey @carolstran, thank you very much for your message.

I already thought about what can I talk about in 10 minutes. So, yes, no problem :) But actually would be great if I could get a full slot. Because I'd like to enrich the talk with some anecdotes and examples to make it more entertaining as well :)

I'm ok with either way. Have a good day 🖖

**Comment by carolstran** [comment]
Great! I marked you down as being open to a lightning talk. Once I hear back from everyone I'll know more about how it can all fit together. 

If you'd prefer to give a regular-length talk then I'm guessing we could have you on by early 2020 😁 The dates for Q1 are January 16, February 20 and March 19 if any of those already look good to you.

**Comment by yatki** [comment]
@carolstran January 16 looks good to me at the moment. If there is a chance to give the short version of the talk before that, I'd still like to do it :) I think it still would be valuable. Just let me know if there is a slot for that.

Have a great week.

**Comment by carolstran** [comment]
👋 Hello again! If you'd prefer to give a 5-10 minute version of your talk, then we can fit you in this year for sure. Are you available for either the September 19, October 17 or November 21 meetup?

**Comment by yatki** [comment]
I'm available at September 19 for sure and it fits perfectly. I'm not sure about about the following months since I don't plan that ahead 😅 But probably I'd be available, I can schedule myself accordingly.

**Comment by carolstran** [comment]
Sounds good! Let's consider you confirmed to give a 10-minute talk at the September meetup and we'll check in again towards the end of August 😊

**Comment by yatki** [comment]
@carolstran Lovely, thank you very much! Looking forward for it.

**Comment by carolstran** [comment]
👋 @yatki  

Just wanted to check in to see if you're still available and want to give a lightning talk at our meetup on September 19? And if so, is the title and abstract you provided above correct?

If you could let me know either way by the end of the month, that'd be excellent 😁

**Comment by yatki** [comment]
Hey @carolstran. Yes I'm still available and looking forward to it. 

I'm currently working on a new title and a summary but just to give you an idea, I'll talk about how can we standardize testing by going through testing types, test doubles and some guidelines to follow to have 100% confidence to our tests and avoid having brittle tests in future. 🖖

**Comment by carolstran** [comment]
Awesome! Thanks @yatki. Can you send me the new title/summary by the end of next week?

**Comment by carolstran** [comment]
Just FYI we added the other talks to the website, but we'll wait until we have your updated title/abstract to announce the meetup 😁

**Comment by yatki** [comment]
Hey @carolstran, sorry for the late reply. I got sick during my vacation 😅 🤦‍♂ 

So, I'd like to change the title and abstract as below:

Title: One guideline to test them all
Abstract: 
Testing itself is one of the most controversial and opinionated topics in dev world. Not because it's complicated, but because it's not standardised. Let's change that together. I'd like to share a handbook that thought me how to listen to my tests, what did my tests say about my code and how they eventually made me a better developer.

In this talk I'll focus on how to end 2 most frequently debated topics:
- How to organise test types?
- How to use test doubles?

---

Also one question for you @carolstran. Are the talks being recorded? Do you have equipment for that or should we do it ourselves?

Cheers,

**Comment by carolstran** [comment]
Ahhh that happened to me last week too! Hope you're feeling better 🍵 💐 

The title and abstract look great, thank you! I'll update the website today probs. 

We don't record our meetups because we want to make the atmosphere as welcoming as possible for first-time speakers. If you're interested in recording yourself though and have the equipment... that might be possible? Looping in @rmehner because he'll actually be there in September (I'll be on vacation again 😎)

**Comment by carolstran** [comment]
Alright @yatki you're up on the website! https://berlinjs.org/ 

We'll announce the meetup next week 🏄‍♀

**Comment by yatki** [comment]
@carolstran That's great. Thank you very much. Looking forward to be there 🖖

**Comment by carolstran** [comment]
Thank you again for speaking! I heard it went very well and I'm happy we finally got to have you on stage 🕺  Closing this issue now 👋

**Comment by yatki** [comment]
Hey @carolstran, thank you very much for the opportunity. It was a great experience. 
Also, could you please take a look at my messages on twitter. I couldn't get a response for a while there. 😄 

Have a great week and hope to see you soon in the next events. 🖖
