### ISSUE TITLE
Talk proposal: Handling a JSONP nightmare

### ISSUE THREAD

**Issue by viniciuskneves** [berlinjs/berlinjs.org#288]
##### Abstract

Based on this blog post (https://medium.com/@viniciuskneves/handling-a-jsonp-nightmare-3865c9d8bfdd) I want to show how I implemented a solution for a big problem I faced using JSONP once.
I know JSONP is quite an old topic but I think it is interesting and it shows how you could deal with some CORS issues in the past, especially for third-party integrations.

###### Your name

Vinicius Kiatkoski Neves

###### Means to get in touch with you

BerlinJS Slack: viniciuskneves
Twitter: @viniciuskneves

**Comment by carolstran** [comment]
Oh hey again @viniciuskneves! 

Out of the two talks you've proposed, which one would you be more interested in presenting? Also same question I left on the other issue applies - would you be open to giving a 5-10 minute version of this talk?

**Comment by viniciuskneves** [comment]
Hey @carolstran, I think I can manage to do this one in 10min if I rush a bit I think.

Just want to make sure it fits the schedule and it is not just because I proposed 2 talks hehehe

https://github.com/berlinjs/berlinjs.org/issues/280#issuecomment-504774789 as reference

**Comment by carolstran** [comment]
No I'm asking everyone if they'd be willing to give a shorter version of their talk so we can get more people on stage this year ⚡️  

But it'd be great if you could choose which topic you're more interested in presenting (or if you're not sure, I can talk to my co-organizers and we can choose). That way we can plan for that one and close the other 😊

**Comment by viniciuskneves** [comment]
Oh, cool. Got it!

Yeah, I would like to present this one as there were other people talking about async/await and Javascript engine this year.

Thanks! 😄

**Comment by carolstran** [comment]
Cool! Would you still be open to giving a shorter version? Or rather wait to give the full length? Based on the current waitlist, I would guess the full-length slot will come up in Q1 2020.

**Comment by viniciuskneves** [comment]
I could make the shorter version of this one 😄

**Comment by carolstran** [comment]
Awesome! Still have a few people to hear back from but then I'll let you know.

**Comment by carolstran** [comment]
👋 Hello again! If you'd prefer to give a 10-minute version of your talk, then we can fit you in this year for sure. Are you available for either the October 17 or November 21 meetup?

**Comment by viniciuskneves** [comment]
November 21st I might be in Brazil :/
October 17th is OK.

Just to make sure: Up to 10min talk, right?

**Comment by carolstran** [comment]
Hey @viniciuskneves, we also now have an opening for our September 19 meetup is that works better for you! Otherwise, October is good too. Up to 10 minutes yes 😊

**Comment by viniciuskneves** [comment]
Hey @carolstran, better keep October as I will have friends around in September and probably won't have enough time throughout the month. Thanks for asking!

**Comment by carolstran** [comment]
Sounds good! I'll consider you confirmed for October and check in again closer to 😊

**Comment by carolstran** [comment]
Hey hey @viniciuskneves, just wanted to check in and see if you're still up for giving a talk at our meetup later this month (October 17) 👻  And if yes, then please let me know if you want to make any changes to your title/abstract before we add it to the website 🎃

**Comment by viniciuskneves** [comment]
Hey @carolstran 
 I will update the abstract probably. When is the deadline?
Just to make sure, it is still lightning talk, right?
Thanks for the ping!

**Comment by carolstran** [comment]
Deadline hmmmm.... end of the weekend? It'd be great to announce the speakers early next week 🙌 

And yes! Still a lightning talk ⚡️

**Comment by viniciuskneves** [comment]
Hey @carolstran, here is a better abstract than the one I presented previously. See you in a few days 😄 

Abstract:

JSONP is an old topic but when you work with different integrations/clients you can expect everything to happen. I used to work for a recommendation systems company so our clients were e-commerce stores. Sometimes we needed to do customize our solutions to them. Here began my issue. One of these custom features was to use what we called “price API”. The name is self-explainable but it is an API where I could fetch a product’s price. It is very useful and can even have custom stuffs related to client business. One client decided to do such API using JSONP, so far so good, but the callback param couldn’t be modified (don’t ask me why). Here I had to use my creativity and create a custom but interesting solution.

**Comment by carolstran** [comment]
Great, so I've updated the website - just let me know if we should change anything: https://berlinjs.org/ Planning to announce on Twitter tomorrow!

**Comment by carolstran** [comment]
👋 @viniciuskneves, thank you again for giving a talk at our October meetup! I'm bummed that I missed it but it looks it was a hit. I'll close the issue now, but always feel free to reach out 😊
