### ISSUE TITLE
Talk Proposal: Fetch me if you can - How to handle third party API data in React, Vue, and Svelte

### ISSUE THREAD

**Issue by stiwwelll** [berlinjs/berlinjs.org#294]
### Talk title 

Fetch me if you can - How to handle third party API data in React, Vue, and Svelte

 ### Abstract 

Fetching and displaying third party API data has become a very popular coding challenge, either before or during interview processes. Having seen several candidates going through this exercise, I'd like to walk you through on how to do this in React, Vue and Svelte, show you pitfalls and common struggles, and explain what the interviewer wants to learn about your skill set with this approach

### Your name

Marco

### Contact Details

@MaPagni

### Code of Conduct

- [x] I've read and agree to the [BerlinJS Code of Conduct](http://berlincodeofconduct.org/)

**Comment by carolstran** [comment]
Hey thanks for submitting @stiwwelll 😊 and hope the birthday party was fun 🎉  Based on our previous conversation over Twitter DM, would either the October 17 or November 21 meetup work for you?

**Comment by carolstran** [comment]
Just to let you know, one of our speakers for September had to cancel so we now have an opening for the September 19 meetup as well if that works for you. Just let us know!

**Comment by stiwwelll** [comment]
Hey @carolstran. Thanks a lot for letting me know. I could present at any of those dates. Just let me know where in your opinion I would fit in best.

Regarding the birthday party...a party weekend in Berlin is nothing compared to hosting a kids party. 😁

**Comment by carolstran** [comment]
Hey that's great 🎉 I'll put you down for September for now and check in again towards the end of August 😊

**Comment by stiwwelll** [comment]
Thank you so much for accepting my proposal @carolstran 🎉. This is super exciting! :)

**Comment by carolstran** [comment]
👋 @stiwwelll  

Just wanted to check in to see if you're still available and want to present at our meetup on September 19? And if so, is the title and abstract you provided above correct?

If you could let me know either way by the end of the month, that'd be excellent 😁

**Comment by stiwwelll** [comment]
Hey @carolstran.

Sorry for keeping you hanging. Missed the notification on this one. And I'm still available, YES! :)

Title and abstract would still be the same.

Looking forward to the talk! 🎉

**Comment by carolstran** [comment]
Hey @stiwwelll 👋 I've added you to the website! https://berlinjs.org/ Now we're just waiting to add one more speaker before announcing.

Quick question though: Is there any way we could shorten your title a little? 😁 If you'd rather keep it the way it is, no problem - just wanted to check.

**Comment by stiwwelll** [comment]
Oh my...it's seriously happening. :)

How about...

Fetch me if you can - Handling API data in your favorite* JS framework

What do you think @carolstran ?

**Comment by carolstran** [comment]
Perfect! Thank you 🙏

**Comment by stiwwelll** [comment]
Or wait @carolstran.

Perhaps...`Fetch me if you can - Handling API data in different JS frameworks`

I don't want to impose to anyone that those are their favorite frameworks/libraries. :)

**Comment by carolstran** [comment]
Oooooh even better! I'll update.

**Comment by stiwwelll** [comment]
Thanks a lot and sorry for the back and forth...

**Comment by carolstran** [comment]
Don't apologize! This is no problem 😊

**Comment by carolstran** [comment]
Thank you again for speaking! I heard it went very well and I hope you enjoyed it (and maybe want to do it again hehee) 💃 Closing this issue now 👋

**Comment by stiwwelll** [comment]
@carolstran Thanks a lot for having me. I enjoyed it a lot and hope that I can come back soon. :)
