### ISSUE TITLE
Talk Proposal: Conducting Effective Code Reviews

### ISSUE THREAD

**Issue by ubenzer** [berlinjs/berlinjs.org#299]
### Talk title
Conducting Effective Code Reviews

### Abstract 
Code review is serious business. It is one of the defenses against introducing bugs into the codebase. In this talk, I will talk about:

- What can machines auto code review for us and why
- What should a human check while reviewing (common errors, best practices, etc.)
- How to communicate in the progress of code reviewing

I prepared a blog post about this, currently in editorial review to get published at [Auth0 blog](https://auth0.com/blog/). I'll base my presentation out of that.

### Your name (and pronouns)
Umut Benzer (he)

- [x] This will be my first tech talk (in English)

### Contact Details

[@UmutBenzer](https://twitter.com/UmutBenzer)
umutbenzer@gmail.com
[benzer.dev](https://benzer.dev)

### Code of Conduct

- [x] I've read and agree to the [BerlinJS Code of Conduct](http://berlincodeofconduct.org/)

**Comment by carolstran** [comment]
👋 @ubenzer, thanks for submitting a talk to our meetup! Great topic as well, I've been having many conversations at work around code reviews and how they can best be done - so I'm excited to see it!

Would you be available for our meetup on Thursday, November 21?

**Comment by ubenzer** [comment]
November 21 sounds good to me.  👍

**Comment by carolstran** [comment]
Awesome! You're confirmed for November and we'll check in again closer to 😊

**Comment by ubenzer** [comment]
FYI, the blog post I mentioned is published. My talk will be based on https://auth0.com/blog/conducting-effective-code-reviews/

**Comment by carolstran** [comment]
Hey hey @ubenzer, just wanted to check in and see if you're still up for giving a talk at our meetup later this month (November 21) 🍰 And if yes, then please let me know by the end of the week if you want to make any changes to your title/abstract before we add it to the website! 

We're aiming to announce the lineup next week 😊

**Comment by ubenzer** [comment]
Hi @carolstran . I am good to go on November 21st. 

I previously presented this talk on Node.js Meetup Berlin on 8th of October. Please let me now, if you are not okay with re-presenting the same topic or want to give someone else honors to present. It took about 40 minutes there, I'll chop it down a bit to 15~20 minutes.

Here is a slightly modified abstract:

## Talk title
Conducting Effective Code Reviews

## Abstract
Code review is a serious business. But it is still fun! It is one of the defenses against introducing bugs into the codebase. In this talk, I will talk about the importance of automation, what to pay attention to while reviewing code and how to communicate in the progress of code reviewing.

Based on [this post](https://auth0.com/blog/conducting-effective-code-reviews/).

**Comment by carolstran** [comment]
Hey @ubenzer, don't worry! Totally fine to present on the same topic, especially since we tend to have a different crowd than the Node.js meetup anyway. Cutting it down to a maximum of 20 minutes would be great though since we have a packed schedule 😊 

Thanks and looking forward to it!

**Comment by ubenzer** [comment]
Hi 👋 ,
Thanks for the opportunity. It was a great evening!

**Comment by rmehner** [comment]
@ubenzer thanks again for speaking at our event, it was an excellent talk!
