### ISSUE TITLE
Talk Proposal: When an error is not an exception

### ISSUE THREAD

**Issue by XVincentX** [berlinjs/berlinjs.org#302]
### Talk title

When an error is not an exception

### Abstract 

In this presentation we'll go over some of the unique requirements of [Prism](https://github.com/stoplightio/prism) that made me rewire the brain about the way we think about an Error. People will learn the particular domain of Prism, understand why throwing an exception is not an option and what the tooling is available today in JavaScript/TypeScript to model such abstraction correctly.

### Your name (and pronouns)

Vincenzo Chianese (he/him)

### Contact Details

Twitter: d3dvincent
GitHub: XVincentX

### Code of Conduct

- [x] I've read and agree to the [BerlinJS Code of Conduct](http://berlincodeofconduct.org/)

**Comment by carolstran** [comment]
Hey hey @XVincentX! Apologies for my delay, but thanks for submitting a talk 🙌 I've added you to our internal waitlist and we'll let you know when we'll be able to have you.
