### ISSUE TITLE
Talk Proposal: Ad Creative Apps

### ISSUE THREAD

**Issue by jacekbj** [berlinjs/berlinjs.org#310]
### Abstract 

At Fandom we built a setup to develop custom "apps" (think: micro frontends) to multiple platforms we support. Apps are delivered in an unconventional way: through an ad server. We use the apps to run UX experiments centered around ad layouts and forms.

I will start with explaining how ad stack works (in a very simplified way to establish common ground).
Then I will proceed to outline how to deliver custom code through the ad server. I will say a few words about communication between micro frontends and how we iterate fast with the use of end to end tests.
I want the talk to be at basic level so that a wide audience can enjoy it.

### Jacek Broński-Jankowski (he/him)

At Fandom I have the unique opportunity to interact with hundreds of millions of unique visitors a month. My team and I juggle JS and data processing tools in a data-driven effort to improve user experience while the meet the needs of publishers. This poses challenges from fields of web performance, UX and statistics.

I gave two talks at local meetups in Poznan:
Front.Radar #2 (organized by Merixstudio)
Chill.js (organized by Netguru)
(talks about Web Components)

### Contact Details

jacek.j.jankowski@gmail.com
www.linkedin.com/in/jacek-bj
https://github.com/jacekbj

### Code of Conduct

- [x] I've read and agree to the [BerlinJS Code of Conduct](http://berlincodeofconduct.org/)

**Comment by carolstran** [comment]
Hey @jacekbj, thanks for submitting a talk! I've added you to our waitlist and we'll reach out again when we have a better idea of our 2020 schedules 😊

**Comment by jacekbj** [comment]
Perfect, I will keep an eye out for updates.
