### ISSUE TITLE
improving workflow for submitting talks

### ISSUE THREAD

**Issue by timaschew** [berlinjs/berlinjs.org#95]
@rmehner I write some notes down, from our discussion after the last talk.

Primary goals:
- No dev setup of ruby or node for the user, ideally the users only needs a browser
- Ideally the user doesn't need any social account (github, twitter, etc.) at least an email
- A preview of the website with the submitting talk for the user
- Accepting the talk via a pull request on github (current state)
- Deploying website via github pages (current state)

Content the user can type in:
- title
- name (optinal with an link to twitter, etc)
- description with simple formatting (markdown)
  - regular, bold, italic, links, quotes

Please let me know if I misunderstand or miss something

**Comment by rmehner** [comment]
On 21.01.2014, at 00:28, Anton Wilhelm notifications@github.com wrote:

> @rmehner I write some notes down, from our discussion after the last talk.
> 
> Primary goals:
> 
>   • No dev setup of ruby or node for the user, ideally the users only needs a browser

Yup, it should be as easy as possible without any dependencies (if that's possible, and I think it is). We simply want to be most welcoming to everyone and once someone steps up and wants to submit a talk, our system should not be in the way of submitting, potentially leading to frustration and less talks.

>   • Ideally the user doesn't need any social account (github, twitter, etc.) at least an email

My idea was: Try with GitHub account if it's there, if not just use email.

>   • A preview of the website with the submitting talk for the user
>   • Accepting the talk via a pull request on github (current state)

That would be ideal. But the most important thing is, that the organizers have it easy to accept talks. I do like pull requests for that if possible, as it allows discussion.

>   • Deploying website via github pages (current state)

As far as I'm concerned that actually doesn't matter too much, if it's the live preview is possible. Right now I do like it though, as it allows to simply clone to repo without much work.

> Content the user can type in:
> 
>   • title
>   • name (optinal with an link to twitter, etc)

Yup, right now we always used Twitter if possible, as this allows the attendees to contact the speakers after the talk very easily.

>   • description with simple formatting (markdown)
>       • regular, bold, italic, links, quotes
> Please let me know if I misunderstand or miss something

Thanks for your effort. I made some free time on this weekend to play around with the above in a separate branch, maybe we can work on this together then :)

**Comment by localheinz** [comment]
Do I understand correctly that you're trying to implement a workflow where
- a consumer can use a web interface (a form) to provide details in order to submit a talk
- on submission of the form a PR is issued against the `gh-pages` branch

. . . ?

**Comment by rmehner** [comment]
That was one idea we wanted to try out, yes. The twist would be, that the form would do some magic to allow a "live preview" feature, without depending on the user to install some ruby/node/whateverfloatsyourboat on their machine.

**Comment by localheinz** [comment]
That would be quite cool, actually!

**Comment by timaschew** [comment]
Great!
I already started here: https://github.com/timaschew/berlinjs.org
@rmehner work remotely or physically together?

**Comment by rmehner** [comment]
@timaschew depends, I wanted to get my hands on this Saturday/Sunday, so I guess remote in first place. But I'm happy to meet in person once there is something to show / discuss. As for using a static site generator: We already have that, thanks to @localheinz in #88 and in berlinjs/new-berlinjs.org#4 (for our new website). But it's definitely given that node is easier to install than ruby for a regular user :)

**Comment by timaschew** [comment]
@rmehner there is not much visual stuff to show yet.
My initial intention was to do this primary for the next berlinjs talk as a use case / example for docpad (nodejs static site generator, like jekyll.
But it becomes more than static site stuff. I created a automated workflow for the git stuff (fork, change, commit, pull request), the focus is more on the automated git workflow than on the static site generator.

So I'm not sure if I should put it all together in one talk - and if yes, what the topic should be.

Are there any visual design changes in #88 or https://github.com/berlinjs/new-berlinjs.org/pull/4 compared to the current version, and which are the newer / should become the official website?

**Comment by timaschew** [comment]
First crosscut implementation.
I told it at hack and tell: http://www.youtube.com/watch?v=q1KBJin4U08

**Comment by mbesser** [comment]
Wow. That's looks pretty impressive. It's very close to the solution i dreamed of, but couldn't code for myself ;-)

**Comment by CelineausBerlin** [comment]
Yeah!

**Comment by finnp** [comment]
I like how the Ruby Berlin Community handles this: http://www.rug-b.de/. People can can vote for talk ideas and everything. It is a different workflow, but I think a nice one. The code is Open Source over here: https://github.com/phoet/on_ruby
